// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqRN7NDc8A0JvZe_-ri1rUW7H7_I9UUGY',
    appId: '1:558909977932:web:2b7eb763469d8cfaff4be9',
    messagingSenderId: '558909977932',
    projectId: 'examnow-ed2f5',
    authDomain: 'examnow-ed2f5.firebaseapp.com',
    storageBucket: 'examnow-ed2f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB989qBtj21C-fGGnRrlYCh06Yei68xN3Q',
    appId: '1:558909977932:android:0338d038843bdfa9ff4be9',
    messagingSenderId: '558909977932',
    projectId: 'examnow-ed2f5',
    storageBucket: 'examnow-ed2f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiXAI3Fz3Mpst8nmw7k4efiH49HtorrjQ',
    appId: '1:558909977932:ios:7fb782b303923c5fff4be9',
    messagingSenderId: '558909977932',
    projectId: 'examnow-ed2f5',
    storageBucket: 'examnow-ed2f5.firebasestorage.app',
    iosBundleId: 'com.example.examnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiXAI3Fz3Mpst8nmw7k4efiH49HtorrjQ',
    appId: '1:558909977932:ios:7fb782b303923c5fff4be9',
    messagingSenderId: '558909977932',
    projectId: 'examnow-ed2f5',
    storageBucket: 'examnow-ed2f5.firebasestorage.app',
    iosBundleId: 'com.example.examnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqRN7NDc8A0JvZe_-ri1rUW7H7_I9UUGY',
    appId: '1:558909977932:web:3b1c9dabb3d0b6a7ff4be9',
    messagingSenderId: '558909977932',
    projectId: 'examnow-ed2f5',
    authDomain: 'examnow-ed2f5.firebaseapp.com',
    storageBucket: 'examnow-ed2f5.firebasestorage.app',
  );
}
